// Package generate builds the rdk-managed tree from parsed definitions.
// Build is pure: same definitions, same rdk binary -> byte-identical Tree.
package generate

import (
	"embed"
	"fmt"
	"io/fs"
	"path"
	"strings"

	"github.com/jarrod-lowe/rdk/internal/parse"
)

//go:embed modules
var moduleFS embed.FS

// Tree maps managed-dir-relative paths to file contents.
type Tree map[string][]byte

const readme = `# Generated by rdk — DO NOT EDIT

Everything in this directory is deleted and rewritten by ` + "`rdk apply`" + `.
Edit the definitions in ` + "`rdk/`" + ` instead.
`

// Build produces the full managed tree for the given definitions.
func Build(defs []parse.Definition) (Tree, error) {
	tree := Tree{"README.md": []byte(readme)}

	tf, err := tfJSON(defs)
	if err != nil {
		return nil, err
	}
	tree["terraform/main.tf.json"] = tf

	// Vendor the embedded module source for every kind in use (DD-2: vendored).
	used := map[string]bool{}
	for _, d := range defs {
		if d.Kind != "config" {
			used[d.Kind] = true
		}
	}
	for kind := range used {
		if err := vendorModule(kind, tree); err != nil {
			return nil, err
		}
	}
	return tree, nil
}

func vendorModule(kind string, tree Tree) error {
	return vendorModuleFS(moduleFS, kind, tree)
}

// vendorModuleFS walks the module source rooted at modules/<kind> in fsys and
// writes each file into tree under terraform/modules/<kind>/, PRESERVING the
// file's path relative to the module root (never flattening subdirectories —
// a flatten would silently collide nested files that share a basename).
func vendorModuleFS(fsys fs.FS, kind string, tree Tree) error {
	src := "modules/" + kind
	return fs.WalkDir(fsys, src, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return fmt.Errorf("embedded module %q: %w", kind, err)
		}
		if d.IsDir() {
			return nil
		}
		content, err := fs.ReadFile(fsys, p)
		if err != nil {
			return err
		}
		sub := strings.TrimPrefix(p, src+"/") // path relative to the module root
		rel := path.Join("terraform/modules", kind, sub)
		tree[rel] = content
		return nil
	})
}
