// Package generate builds the rdk-managed file set from parsed definitions.
// Build is pure: same definitions, same rdk binary -> identical FileSet.
package generate

import (
	"embed"
	"fmt"
	"io/fs"
	"path"
	"strings"

	"github.com/jarrod-lowe/rdk/internal/parse"
	"github.com/jarrod-lowe/rdk/internal/repofs"
)

//go:embed modules
var moduleFS embed.FS

const readme = `# Generated by rdk — DO NOT EDIT

Everything in this directory is deleted and rewritten by ` + "`rdk apply`" + `.
Edit the definitions in ` + "`rdk/`" + ` instead.
`

// Build produces the managed file set for the given definitions.
func Build(defs []parse.Definition) (*repofs.FileSet, error) {
	set := repofs.NewFileSet()
	set.Bytes("README.md", []byte(readme))
	if err := set.JSON("terraform/main.tf.json", tfDoc(defs)); err != nil {
		return nil, err
	}

	used := map[string]bool{}
	for _, d := range defs {
		if d.Kind != "config" {
			used[d.Kind] = true
		}
	}
	for kind := range used {
		if err := vendorModule(kind, set); err != nil {
			return nil, err
		}
	}
	return set, nil
}

// vendorModule copies the embedded module source for kind into the set under
// terraform/modules/<kind>/, preserving subdirectories.
func vendorModule(kind string, set *repofs.FileSet) error {
	src := "modules/" + kind
	return fs.WalkDir(moduleFS, src, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return fmt.Errorf("embedded module %q: %w", kind, err)
		}
		if d.IsDir() {
			return nil
		}
		content, err := fs.ReadFile(moduleFS, p)
		if err != nil {
			return err
		}
		sub := strings.TrimPrefix(p, src+"/")
		set.Bytes(path.Join("terraform/modules", kind, sub), content)
		return nil
	})
}
